const { withAndroidManifest } = require('@expo/config-plugins');

/**
 * Declares the packages Pinch needs to detect as installed.
 *
 * Android 11 (API 30) locked down package visibility: an app can no longer
 * see whether another app is installed unless it is named in a <queries>
 * block in the manifest. Without this, Linking.canOpenURL('whatsapp://...')
 * always returns false regardless of whether WhatsApp is actually on the
 * phone — silently falling through to the generic share sheet instead of
 * opening WhatsApp with the debt reminder pre-filled and ready to send.
 *
 * A local config plugin because android/ is regenerated by `expo prebuild
 * --clean`; hand-editing the generated manifest would be lost on the next
 * prebuild.
 */
const WHATSAPP_PACKAGES = ['com.whatsapp', 'com.whatsapp.w4b'];

module.exports = function withPackageQueries(config) {
  return withAndroidManifest(config, (config) => {
    const manifest = config.modResults.manifest;
    if (!manifest.queries) manifest.queries = [{}];
    const queries = manifest.queries[0];
    if (!queries.package) queries.package = [];

    for (const packageName of WHATSAPP_PACKAGES) {
      const already = queries.package.some(
        (entry) => entry.$?.['android:name'] === packageName
      );
      if (!already) {
        queries.package.push({ $: { 'android:name': packageName } });
      }
    }

    return config;
  });
};
